### ISSUE TITLE
Bake the dependency (and runner config) into Cucumber-JVM

### ISSUE THREAD

**Issue by mattwynne** [cucumber-ltd/cucumber-pro-plugin-jvm#26] opened 2018-03-14 10:50 UTC
User feedback we're getting shows that the current three-step process (add to `pom`, annotate runner(s), create config file) is creating friction when on-boarding new users.

We'd like to ease this by shipping future versions of Cucumber-JVM with the plugin dependency, and having the plugin auto-loaded if it looks like Cucumber is running in a CI environment.

**Comment by aslakhellesoy** [comment] 2018-03-14 12:26
Dupe of #2

**Closed as completed by aslakhellesoy** 2018-03-14 12:26 UTC
